[supervisord]
nodaemon=true

[program:rails]
directory=/app/rails
command=bundle exec puma -C config/puma.rb
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="3000",RAILS_ENV="production",SECRET_KEY_BASE="%(ENV_SECRET_KEY_BASE)s"

[program:goapi]
command=/app/api/schola-theologiae-api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="%(ENV_PORT)s"
